// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package ingector

import (
	"context"
	"openappsec.io/smartsync-shared-files/internal/app"
	"openappsec.io/smartsync-shared-files/internal/app/drivers/http/rest"
	"openappsec.io/smartsync-shared-files/internal/app/sharedfiles"
	"openappsec.io/smartsync-shared-files/internal/pkg/filesdb/filesystem"
	"openappsec.io/configuration"
	"openappsec.io/configuration/viper"
	"openappsec.io/health"
)

// Injectors from wire.go:

func InitializeApp(ctx context.Context) (*app.App, error) {
	adapter := viper.NewViper()
	service, err := configuration.NewConfigurationService(adapter)
	if err != nil {
		return nil, err
	}
	healthService := health.NewService()
	filesystemAdapter, err := filesystem.NewAdapter(service)
	if err != nil {
		return nil, err
	}
	sharedfilesService, err := sharedfiles.NewSharedFilesService(filesystemAdapter)
	if err != nil {
		return nil, err
	}
	restAdapter, err := rest.NewHTTPAdapter(ctx, service, healthService, sharedfilesService)
	if err != nil {
		return nil, err
	}
	appApp := app.NewApp(restAdapter, service, healthService)
	return appApp, nil
}
